Switched to bionic OS platform and enabled JDK 1.8 for sdkmanager

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,11 +1,19 @@
-dist: trusty
+dist: bionic
 language: generic
 os:
   - linux
 #  - osx
 #services:
 #  - xvfb
+
+# specify global envs and jobs
 env:
+  global:
+    - ANDROID_TOOLS=4333796 # android-28
+    - ANDROID_HOME=${HOME}/android-sdk
+    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
+    - JDK="1.8" # used while running sdkmanager, otherwise uses default JDK
+  jobs:
 #  - SYS=25 ABI="google_apis;arm64-v8a"
   - SYS=25 ABI="google_apis;armeabi-v7a"
 #  - SYS=24 ABI="google_apis;arm64-v8a"
@@ -41,7 +49,7 @@ env:
 #    - env: SYS=14 ABI="default;armeabi-v7a"
 
 before_install:
-  - java -version
+  - java -version || : # noop, ignore failure
 #  - |
 #    if [ $TRAVIS_OS_NAME == "linux" ]; then
 #      export DISPLAY=:99.0
@@ -49,7 +57,15 @@ before_install:
 #      sleep 3 # give xvfb some time to start
 #    fi
 
+  # Set up JDK 8 for Android SDK
+  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
+  - export TARGET_JDK="${JDK}"
+  - JDK="1.8"
+  - source ~/.install-jdk-travis.sh
+  -
   # Install android tools
+  - sudo apt-get -y --no-install-recommends install libpulse0 # required by emulator
+  - sudo apt-get -y --no-install-recommends install libxcursor1 # required by emulator
   - ANDROID_TOOLS=4333796 # android-28
   - export ANDROID_HOME=~/android-sdk
   - |
@@ -95,7 +111,12 @@ before_install:
       EMU_PARAMS="-no-boot-anim -gpu off"
     fi
     # use the absolute emulator path in case older version installed (on default path)
-    $ANDROID_HOME/emulator/emulator -avd test -no-audio $EMU_PARAMS $EMU_ADDITIONAL_OPTIONS ${EMU_DEBUG} &
+    $ANDROID_HOME/emulator/emulator -verbose -avd test -no-audio $EMU_PARAMS $EMU_ADDITIONAL_OPTIONS ${EMU_DEBUG} &
+
+  # Switch back to our target JDK version to build and run tests
+  - JDK="${TARGET_JDK}"
+  - source ~/.install-jdk-travis.sh
+
 before_script:
   # Wait for emulator to startup.
   - ./scripts/android-wait-for-emulator.sh
